import { Inter } from 'next/font/google'
import './globals.css'
import Sidebar from './components/layouts/Sidebar'
import Navbar from './components/layouts/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="grid grid-cols-12">
          <div className="col-span-1">
            <Sidebar />
          </div>
          <div className="col-span-11">
            <Navbar />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
